package azureaisearch

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

type IndexOption func(indexMap *map[string]interface{})

func (s *Store) CreateIndex(ctx context.Context, indexName string, opts ...IndexOption) error {
	defaultIndex := map[string]interface{}{
		"name": indexName,
		"fields": []map[string]interface{}{
			{
				"key":        true,
				"name":       "id",
				"type":       FieldType_string,
				"filterable": true,
			},
			{
				"name":       "content",
				"type":       FieldType_string,
				"searchable": true,
			},
			{
				"name":       "contentVector",
				"type":       CollectionField(FieldType_single),
				"searchable": true,
				// dimensions is the number of dimensions generated by the embedding model. For text-embedding-ada-002, it's 1536.
				// basically the length of the array returned by the function
				"dimensions":          1536,
				"vectorSearchProfile": "default",
			},
			{
				"name":       "metadata",
				"type":       FieldType_string,
				"searchable": true,
			},
		},
		"vectorSearch": map[string]interface{}{
			"algorithms": []map[string]interface{}{
				{
					"name": "default-hnsw",
					"kind": "hnsw",
					"hnswParameters": map[string]interface{}{
						"m":              4,
						"efConstruction": 400,
						"efSearch":       500,
						"metric":         "cosine",
					},
				},
			},
			"profiles": []map[string]interface{}{
				{
					"name":      "default",
					"algorithm": "default-hnsw",
				},
			},
		},
	}

	for _, indexOption := range opts {
		indexOption(&defaultIndex)
	}

	if err := s.CreateIndexAPIRequest(ctx, indexName, defaultIndex); err != nil {
		fmt.Printf("error creating index: %v\n", err)
		return err
	}

	return nil
}

func (s *Store) CreateIndexAPIRequest(ctx context.Context, indexName string, payload any) error {
	URL := fmt.Sprintf("%s/indexes/%s?api-version=2023-11-01", s.cognitiveSearchEndpoint, indexName)
	body, err := json.Marshal(payload)

	if err != nil {
		fmt.Printf("err marshalling json: %v\n", err)
		return err
	}

	req, err := http.NewRequest(http.MethodPut, URL, bytes.NewBuffer([]byte(body)))

	if err != nil {
		fmt.Printf("err setting request for index creating: %v\n", err)
		return err
	}

	req.Header.Add("Content-Type", "application/json")
	if s.cognitiveSearchAPIKey != "" {
		req.Header.Add("api-key", s.cognitiveSearchAPIKey)
	}

	if err := s.HTTPDefaultSend(req, "index creating for cognitive search", nil); err != nil {
		fmt.Printf("err request: %v\n", err)
		return err
	}

	return nil
}
