# https://taskfile.dev

version: '3'

silent: true

tasks:
  default:
    cmds:
      - task --list-all
  run:text-embeddings-inference:
    cmds:
      - text-embeddings-router --model-id thenlper/gte-large --port 5500
